### ISSUE TITLE
Put back 'xblockutils/base_test.py'

### ISSUE THREAD

**Issue by farhan** [openedx/xblock-sdk#345]
The initiator the task is this [PR](https://github.com/open-craft/xblock-poll/pull/127)
Parent Story: https://github.com/openedx/XBlock/issues/675

As the community is using [base_test.py](https://github.com/openedx-unsupported/xblock-utils/blob/7a88cb9b5cc56ff6b23f6ffcb320667b1ea27e92/xblockutils/base_test.py) for plain selenium integration tests that was removed, so let's put it back.

Since base_test.py is tightly coupled with workbench, so lets move it into the xblock-sdk repo and combine it with [test_utils.py](https://github.com/openedx/xblock-sdk/blob/master/workbench/test_utils.py) which seems to have related functionality as suggested [here](https://github.com/open-craft/xblock-poll/pull/127#issuecomment-1883526346)

**Comment by farhan** [comment]
[xblockutils/base_test.py](https://github.com/openedx-unsupported/xblock-utils/blob/7a88cb9b5cc56ff6b23f6ffcb320667b1ea27e92/xblockutils/base_test.py) is extending from [SeleniumTest](https://github.com/openedx/xblock-sdk/blob/e562d9642d458702a6be898d26cb431b644bd67e/workbench/test/selenium_test.py) class which is using `bok-choy`'s [WebAppTest](https://github.com/openedx-unsupported/bok-choy/blob/master/bok_choy/web_app_test.py#L22) class.

So it's linked to `bok-choy` library and I think we should keep it removed

@feanil what are your thoughts on it ?

**Comment by kdmccormick** [comment]
Ah, I thought that `workbench.test.selenium_test.SeleniumTest` was a third-party library. I didn't realize that it actually comes from xblock-sdk and uses bok-choy.

I support keeping it removed 👍🏻 Thanks for looking into that @farhan .
