### ISSUE TITLE
Study and fix crash on updating `lxml==5.1.0`

### ISSUE THREAD

**Issue by farhan** [openedx/xblock-sdk#347]
In the `xblock-sdk` git repository `lxml` has been updated to `5.1.0` in [PR](https://github.com/openedx/xblock-sdk/pull/343#issuecomment-1890801331)

which is crashing the code.
When I run `python manage.py run server` I experience the following crash
```
  File "/Users/farhankhan/.pyenv/versions/xblock-sdk/lib/python3.8/site-packages/xblock/fields.py", line 19, in <module>
    from lxml import etree
ImportError: dlopen(/Users/farhankhan/.pyenv/versions/xblock-sdk/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'
```

I have experienced the same crash when updating `lxml` package [here](https://github.com/farhan/edx-platform/blob/farhan/code-migrated-from-tubular/scripts/user_retirement/requirements/base.txt#L81)

In this ticket, we need to figure out the root cause of it and try to fix it by either via code update to fixing the `lxml` to lower version.

**Some Effected repos:**

- [XBlock ](https://github.com/openedx/XBlock/blob/79817df3247506a85acff308b589179e35ec75fe/requirements/constraints.txt#L17)
- [xblock-sdk](https://github.com/openedx/xblock-sdk/blob/68aa353aa783d1960669c6f82d2fbf56658022a7/requirements/constraints.txt#L13)
- [FeedbackXblock](https://github.com/openedx/FeedbackXBlock/blob/7287f407fbe3fe4563608f7f4d8a6637e92c745b/requirements/constraints.txt#L13)

**Comment by Agrendalath** [comment]
This one also affects the DnDv2 XBlock: https://github.com/openedx/xblock-drag-and-drop-v2/blob/78e4135/requirements/constraints.txt#L19-L20.

**Comment by irtazaakram** [comment]
PRs related to this issue 

https://github.com/openedx/FeedbackXBlock/pull/81
https://github.com/openedx/xblock-lti-consumer/pull/471
https://github.com/openedx/edx-ora2/pull/2207 depends on https://github.com/openedx/i18n-tools/pull/146
https://github.com/openedx/xblock-drag-and-drop-v2/pull/404

**Comment by irtazaakram** [comment]
All PRs have been merged.
